---
engine: knitr
title: Databases and Data APIs
---

## Learning objectives

- Understand how and learn how to access data from a database

- Understand how and learn how to access data from a a REST API

## Database-as-a-service {-}

-   When to use what? **Database** vs **Datawarehouse** vs **Datalake**.

-   Recommended solutions: **EBS**, **RDS**, **Redshift** and **S3**. 

-   Is that all we got? (**Hint**: Not even close!!).

-   Be careful technology != concept/solution (for [storage](https://www.redhat.com/en/topics/data-storage/file-block-object-storage))

## "meet the data where it lives" {-}

- Flat files (csv. xls, parquet)

- Databases

- Web API (usually REST)

- Other cases: videos, sensors, and users input (prob. more!) 

## An easy Example 


```bash
#!/bin/bash

db_set () {
  echo "$1, $2" >> database 
}

db_get (){
  grep "^$1," database | sed -e "s/^$1,//" | tail -n 1
}
```

Very simple implementation[^1] with a lot of problems but...  it saves data and retrieves it!


[^1]: Kleppmann, Martin, author. (2017). [Designing data-intensive applications : the big ideas behind reliable, scalable, and maintainable systems.](https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/) Sebastopol, CA :O'Reilly Media

## The Relational DataBase Management System (RDBMS)[^2]: 
  
Data Isolation: isolate both the OS and user/applications from data representations. 

 - Table (relations) as a data structures 

 - DBMS manages storage 

 - DBMS provides a declarative language to access it

 - Your applications are happy 😀 


```{mermaid, DBMS, echo = FALSE, htmlLabels = FALSE}
flowchart LR
    A[Database Storage] --> B[Physical Schema] --> D[Logical Schema] --> E[Applications]
```

 

[^2]: CMU Database group, [Relational Model & Algebra (CMU Intro to Database Systems)](https://youtu.be/APqWIjtzNGE?si=AHdOjvsjs0vzFSr0)


## Accessing and using databases

In Python:  

```python
import psychopg2
con = psycopg2.connect()
import duckdb
con = duckdb.connect('data/my-db.duckdb')
```

in R: 

```R
con <- DBI::dbConnect(RPostgres::postgres())
con <- DBI::dbConnect(duckdb::duckdb()
```

R use DBI as an abstraction layer between multiple databases drivers. 

The first argument is `drv`

## Credentials 

- Managing them is a pain (Bitwarden, 1password, OS keyring, GH secret, and moarrr!)

- Logic creator > users > viewers

- write / read 

## APIs

- They can be private (localhost) or public 

- Python use `requests` and R use `httr/httr2` (apparently pronounced "hiter") 

- Both are syntaxic sugar (around what?) 

## We will mostly discuss [REST](https://en.wikipedia.org/wiki/REST) API

- See [Web APIs for useRs](https://dru.quarto.pub/web-apis/#/section) from Umair

- Based on http (protocole): 

```{mermaid}
flowchart LR
    Server <--> API <--> Client 
```

- API have path (`/`) and endpoint(s) (`/ping`)

- HTTP Verbs: 95% it will be GET and POST 

## Request Parameters and Bodies

- Defined at endpoint level

- https://newton.now.sh/api/v2/abs/-10 

- Usually you need to use a way to prove you have access: 

    "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/ai/run/@cf/meta/llama-3.1-8b-instruct-fast"

## Request Status Codes

- 20X: all Green

- 4XX: "your fault!" (pb with request)

- 5XX: "server fault"

## Envt variables

- .dotfiles (.Renviron/.Rprofile)

- OS keyring / os.getenv() (os module)

- token-based authorization schemes 


## A package!

```r 
my_db_con <- function(
    user = Sys.getenv("DB_USER"), 
    pw = Sys.getenv("DB_PW"), 
    ..., 
    driver = RPostgres::Postgres()
) {
  DBI::dbConnect(
    driver = driver,
    dbname = 'my-db-name', 
    host = 'my-db.example.com', 
    port = 5432, 
    user = user,
    password = pw, 
    ...
  )
}
```


## Meeting Videos {-}

### Cohort 1 {-}

`r knitr::include_url("https://www.youtube.com/embed/Dh1g_D_Ir0A")`

<details>

<summary>Meeting chat log</summary>
```
00:02:43	Gus Lipkin:	East Coast US, 1pm local
00:44:48	Gus Lipkin:	https://xkcd.com/927/
00:57:17	Jack Penzer:	Graph databases <3
```
</details>
